<?php get_header();

?><main>
    <div class="banner"><h1 class="centered-text"><?php echo get_the_title(); ?></div>
    <br>
    <div class="generic-content two-thirds-screen">
        <h2 class="right-text-no-margin red-brown-text tankindred-text yellow-shadow-heading larger-header">Self-Publishing is a $1.25B industry. Authors take home less than half of that amount. And are subjected to unfair terms & conditions.</h2>
        <h2 class="right-text-no-margin red-brown-text tankindred-text yellow-shadow-heading larger-header">We exist to change that.</h2>
        <div class="orange-line-break"></div>
        <p><a href="https://wordsrated.com/self-published-book-sales-statistics/" target="_blank">Since 2021, self-published authors have generated over a billion dollars in sales per year, while taking home less than a fair share of those dollars.</a> Exploitation stories don't end there. There's the one about <a href="https://goodereader.com/blog/kindle/new-kindle-ebook-return-policy-to-take-effect-at-the-end-of-january" target="_blank">digital returns</a>... Which, they’ve admittedly updated, but eBooks are the only digital items that the behemoth allows. But there’s also that in order to gain the highest return on publication, self-publishers <a href="https://authorlink.com/writing-insights/if-you-self-publish-amazon-who-owns-copyright-2021/" target="_blank">must contract their right to sell elsewhere away</a>… And even though there are now “limits” on the number of books posted per day on that one site… AI is something we’re a bit concerned about. Not just for generated material. But also for <a href="https://www.plagiarismtoday.com/2023/08/09/amazon-and-the-problem-of-reverse-plagiarism/" target="_blank">plagiarism</a>. We are sure there are many more ways self-publishing writers are being exploited. And are committed to doing something about it…</p>
        <p>We believe the time has come for creators - writers, digital cover designers, editors, and small presses to join together with readers to build a community marketplace that we own. When we own, we set the terms for how we are paid. We determine if and how works can be returned. We decide if we want to limit our ability to publish our works elsewhere. Our voices matter. It’s time we bring them together. We are building a cooperative enterprise that serves to move us away from exploitative corporations to community supported publishing.</p>
        <p>Trunk of My Car is a nod to the indie authors who came before us. Pre-internet warriors. The ones who loaded up their cars and posted up outside grocery stores and shopping malls. Those who kept their sales revenue in their communities. We are because they were.</p>
        <p><strong>We are the ones we’ve been writing for.</strong></p>
        <div class="red-orange-line-break"></div>
        <h2 class="large-heading red-brown-text yellow-shadow-heading">Why a Cooperative?</h2>
        <p>The cooperative business model is one that is rooted in community. It’s where we, the people, come together for a common cause and work together to be a solution. Cooperatives exist in every industry. Retail stores, utilities, even restaurants and other services are applying this model that gives the people who use or operate it a say in how they do what they do. We believe that cooperatives are a step away from a capitalistic system that exploits and oppresses individuals, communities, and ultimately, the planet. Want to learn more about cooperatives? Check out <a href="https://ncbaclusa.coop/resources/what-is-a-co-op/" target="_blank">this page</a> the good folks at NCBA put together that breaks this business model down.</p>
            <div class="red-orange-line-break"></div>
        <h2 class="large-heading red-brown-text yellow-shadow-heading">What's In It for We?</h2>
        <p>Shared ownership. Democratic decision making. Collective support. When we move cooperatively, we exchange ‘me’ for ‘we.’ Trunk of My Car Cooperative is a Hawai`i registered multi-stakeholder platform cooperative owned by creators, consumers, and workers. We are not just a marketplace to sell books. We are building sustainable community. We are working together to share knowledge, tools, craft, and space to make all of us better writers, readers, and humans. We will share workshops, craft talks, knowledge based offerings, book clubs, and book swaps - whatever you, our member-owners want to share in community. </p>
        <p>Sounds like something you want to be a part of? <a href="<?php echo esc_url(site_url('/own'));?>">Join us!</a><p>
	</div>
</main>

<?php get_footer(); ?>